function addStudents(L) {
        L.marker([40.42137, -74.67618]).addTo(map)
                .bindPopup("<b>Errol Gingis</b><br />alright welp, i guess ill start. currently back in school workin on associates for computer science to hopefully tfer to rutgers or rider after spring semester. also working at the village school making sure all those little buggers get fed.<br>in case any of you that moved away were wondering if montgomery is still boring as shit... it is. so if you no longer live in this town then enjoy the shit out of that shit cuz this place sucks<br>congrats to any recent/upcoming college grads! I hope to be in your shoes soon. <br> now its your turn!")
        L.marker([40.47868, -74.43126]).addTo(map)
                .bindPopup("<b>Sam Han</b><br />Well whats up, its been a while.<br>Nothing much to say, I joined the service in 2011 proud and happy to serve in the United states army. <br>And yes, I still go to Rutgers <br>Shout out to the service members out there from class of 2010, you know who you are.")
        L.marker([39.34787,-76.618426]).addTo(map)
                .bindPopup("<b>Cassie Passarella</b><br />Hi  I guess I'll go ahead and chime in too. I graduated from Loyola Maryland in May with a degree in history, minor in forensic science. Decided I love forensics, taking a post bacc year and earning a few more prerequisites and will then head to grad school for my MS in forensic science, hopefully specializing in DNA analysis or toxicology. Went to Disney in June with Alex Giannini to celebrate graduation. ")

        L.marker([40.4248126,-74.6745737]).addTo(map)
                .bindPopup("<b>Alex Giannini</b><br />I'll make it quick!! Graduated from University of Delaware in May with a Hotel, Restaurant and Institutional Management major (complicated way of basically saying Business) and animal sciences minor. I was lucky enough to have my parents give me the summer off as a gift since I went to class during breaks to finish in four years. Since then I've been sitting on my ass, sleeping late, and traveling a bit. Went to Europe for a few weeks just got back. I have a pup now who I'm obsessed with. For now am back at home starting the job search. Anyone else who's home has already said the same, yes they're not kidding. Monty IS just as boring as always.")

	L.marker([40.709223,-73.7566123]).addTo(map)
                .bindPopup("<b>Justina Chan</b><br />Hi guys! I just graduated from Drexel in Philly in June with a major in Design & Merchandising, minor in marketing, and a concentration in Retail Buying & Merchandising. Just landed a position in NY and will be starting on Monday! So grateful and excited!")
	
        L.marker([39.982094,-75.154679]).addTo(map)
                .bindPopup("<b>Amanda Moreno</b><br />Hi everyone! Graduated from Temple with a bachelors in anthropology. I'm currently working at an animal hospital and plan on applying to veterinary schools in the next year or so. Hope everyone's doing well!")
	
	
        L.marker([42.345317,-71.042179]).addTo(map)
                .bindPopup("<b>Shrey Singh Bajaj</b><br />What's up everyone, hope you're all doing well in school/with your graduate careers. Anyway, I just graduated from Northeastern and majored in Finance and Accounting. I'm currently working at JP Morgan Chase in Boston so if you're ever in the city, let me know!")
	
	
        L.marker([40.4340645,-74.6336845]).addTo(map)
                .bindPopup("<b>Katie Tonkin</b><br />Just graduated from Messiah College in May with my bachelor's degree in music, joined the Air Force shortly after, and am currently serving in the 193d Special Operations Wing/553d Air Force Band (Guard status). I also somehow swung a new job working for the State of New Jersey Department of Treasury. Still in Monty for the time being. Glad to see everyone doing great things!")

	
        L.marker([27.886051,-82.35824]).addTo(map)
                .bindPopup("<b>Kirstin Hailey</b><br />I guess I'm supposed to say hey y'all since I live in the south now. I moved to Florida with my boyfriend back in January. My dad sold his old bar in New Brunswick and bought a bar in Tampa so my whole family is here too. I'm bartending and working on a website with my brother, which is pretty awesome. My house is a zoo with me and Bryan and our 3 dogs and 2 cats. I might be visiting for thanksgiving if anyone wants to catch up!")
	
	
        L.marker([43.704441,-72.288693]).addTo(map)
                .bindPopup("<b>Kate Stansfield</b><br />This is a kewl idea Kristinith, and who doesn't like talking about themselves!?  So here I go...I graduated from the University of Vermont in May, majored in neuroscience and minored in mathematics. I'm now working as a research assistant/lab manager in a neurobiology lab at Dartmouth and it's awesome. I'm applying to PhD programs either this year or next, haven't decided yet, but my future goal is to end up in good ole Colorado  My folks live in AZ now so I don't go back to Monty much (its boring duh) but probably will at some point. Would be cool to see some of you people!")
	
	
        L.marker([40.423379,-74.7141235]).addTo(map)
                .bindPopup("<b>Robbie Robinson</b><br />Hey everyone! Hope all is well! In regards to me, graduated from Monmouth University this past May! Majored in TV productions, minored in IT! I'm also IT certified! Ran D1 track & field all 4 years while I was there too! Currently, I'm back home in Monty and just started my first part time job doing IT Datatbase for a mailing industry in Lakewood, NJ")

        L.marker([40.4250125,-74.6730535]).addTo(map)
                .bindPopup("<b>Taylor Ann</b><br />Hey everyone ! <br>I graduated In May from La Salle University in Philly studying psychology and criminal justice... I minored in education as well. I went straight into graduate school. I'm currently at Rutgers School of Criminal Justice getting my masters in criminology, I'm very excited to start working in the field next semester. I'm currently focusing on police legitimacy in urban communities and working on research in prison visitation policies and certain collateral consequences and how to better develop integration into the community. I hope to work with the state police in addressing ways to prevent 'crime' and better address police community relationships. It's nice to see that everyone is doing well through the updates !!")
	
		
        L.marker([40.4084797,-74.6715515]).addTo(map)
                .bindPopup("<b>Andrew Sklansky</b><br />Why not? Graduated Ithaca with a Bachelors in History, though I don't really plan on doing anything History related. Currently I'm volunteering with a political group called Wolf-PAC, a group dedicated to getting an amendment passed that will reverse the Citizens United decision, and tomorrow I will be giving a speech, along with others from the group, in front of the New Jersey State Legislature. Other than that, I am also working at Steele's Wine Cellars for some extra money as well continuing to job search. Oh, and me and a couple of buddies are currently creating a hockey website so I might be moving to Connecticut.")



        L.marker([40.268835,-74.78091]).addTo(map)
                .bindPopup("<b>Olivia Lang</b><br />Hey guys! As some of you may already know my life got a little crazy during my time at West Virginia University. Spent two full semesters there and in the middle of my third had some guy get shot and killed up against my car while I was in it SO after a week in witness protection I left! I'm back living in a log cabin house with my boyfriend in Hopewell with my three fur babies while working for a restaurant in New Hope. When I came back from WVU I started classes at Mercer but can only take a few classes a semester because mortgages suck! But, this May I'll have my associates in Humanities and I'll be at TCNJ next fall to finish out my bachelors in...something else? Hope everyone is doing well! If anyone's in Monty I'm just the next town over!")
	
		
        L.marker([39.9624459,-75.1476445]).addTo(map)
                .bindPopup("<b>Sydney Stewart</b><br />Hello All! This is great Kristina! Great reading what you all have been up to I guess I'll share mine. My family has moved out of Montgomery and we currently live in Philadelphia, right in center city. I am finishing up my last year at Northeastern University since it was a five year program. I am studying Communications with a double major in Cinema studies concentration in Production. I have done three co-op's one at BMF Media, another at NBC Universal and just finished my last one working with the Production Management team at BET in New York. When I graduate I will be working as a production assistant on special shows that BET puts on like the BET Awards in LA. Excited for an MHS class of 2010 reunion.")

	
	L.marker([40.4528897,-74.6500936]).addTo(map)
                .bindPopup("<b>Jean Marie</b><br />Hey guys! Last I remember of MHS was telling Mr. Stern to 'go to hell' after getting my diploma. So since then I moved up to New England and went to school for four awesome unforgettable years. I graduated from Roger Williams University in May with a Bachelors in Criminal Justice and a minor in Psych. I moved back home this summer and enjoyed as much of Jersey as I could. I worked at the family tow shop and although we all know Monty is boring I managed to make the best of it with my remaining MHS alumni friends that still live locally. I moved back to Rhode Island last month and began working for the Department of Homeland Security. I officially received my Transportation Security Officer badge today and begin working at T.F. Green Airport tomorrow morning. So if any of you are flying in or out of little rhody anytime soon (I know the chances are slim) let me know and stop by to say hi. Like most I agree this group was a fantastic idea. Hope to keep in touch with you guys and hope all is well.")
	
		
        L.marker([40.3483133,-74.6698424]).addTo(map)
                .bindPopup("<b>Ambika Singh</b><br />Hey guys, so I am still at school at Princeton graduating this year (hopefully haha). I took a year off from school in 2011-2012 for the Olympics in fencing. Was doing very well and right before the Olympics I hurt my hip and got hip surgery so I didn't end up going. I will be going for 2020, skipping 2016 because I want to have a job and be a real person lol. Went back to school and healed within the next year and I am back fencing thankfully. Let me know if you guys are in Princeton, just hit me up if you ever wanna go out ")

	
	L.marker([34.0204989,-118.4117325]).addTo(map)
                .bindPopup("<b>Paul Popescu</b><br />Hi everyone! Thanks Kristina for taking the initiative and making this group a thing! It's been really interesting hearing from everyone who's posted and seeing what you've all been up to since graduation.<br>As for me, I graduated from Princeton in June where I studied English literature. The day after graduation I drove out to LA to start my job at Lionsgate where I work in TV distribution. Little known fact about working in entertainment, the hours are long and the pay is shit, but at least it's never boring!<br>I hope you're all doing well in your post-high school/college lives and I'm looking forward to hearing from more of you!")
	
		
        L.marker([40.651018,-73.871192]).addTo(map)
                .bindPopup("<b>Young-Sun Song</b><br />This is fun. <br>Hey hey~<br>I graduated from Pratt Institute in May with a Bachelor in Fine Arts specifically Jewelery Design. Oh and a minor in Art History. <br>Now I work part time at a small jewelry company and am working to get my own up and running.<br>www.YoungSunSong.etsy.com <br>A shameless promotion. Christmas is coming. Go check it out.<br>I live in Queens NY with a friend who is also in jewelery.<br>It's cool to see what all of you are doing!")



        L.marker([34.102199,-118.3105381]).addTo(map)
                .bindPopup("<b>Marisa Desa</b><br />Hi guys! Let's seeee...graduated in May from UConn with my bfa in acting. I just moved to LA, currently am working as a waitress and trying my hardest to make this actress thing happen. Pretty cliche hah but I really love it out here. Hit me up if any of you are moving or visiting California  btw- who is organizing our reunion?!?! Because I will be back for the holidays and would love to reconnect/get drunk with you lovely people.")
	
		
        L.marker([39.7643389,-104.8551114]).addTo(map)
                .bindPopup("<b>Rachel Kolb</b><br />Hello everyone!! I absolutely love this idea!<br>I'm currently living in Denver, Colorado, I graduated from TCNJ in May with my BS in biomedical engineering and moved here for my masters in bioengineering at CU Denver Anschutz. I'm super interested in neuroscience and i'm working with professors and surgeons at the university & hospital doing research with an implantable Parkinson's device. In my spare time out here I work at lululemon athletica, run half marathons, and i'm anxiously awaiting ski season!<br>If anyone is ever in Denver i'd love to catch up!!")


        L.marker([42.5072444,-83.1575581]).addTo(map)
                .bindPopup("<b>Ryan Maurer</b><br />Hey everyone! It truly has been forever since I've seen the vast majority of you. I hope that changes soon and it's great to read all of your successes!<br>I graduated in May from Central Michigan University with a BSBA in Accounting and Accounting Information Systems. Upon graduation, I started studying for the CPA (Certified Professional Accountant) exam and studied throughout the whole summer. I was still living at school and going to a prep class just about every day. It seemed like a living hell at the time, but man was it worth it! I passed all four sections in those three months, and after one full year of experience I can call myself a CPA!<br>I just recently started working full-time at PricewaterhouseCoopers (PwC), an accounting firm, in mid-August. I'm technically an IT Consultant for SAP systems, but people like to think of me as an auditor (those people are scary). I'm living in Royal Oak, Michigan which is a really young area with an awesome downtown. It's about 20 minutes from downtown Detroit which is where my office is and where my beloved Red Wings play. Living by myself has been an adjustment, but I'm constantly meeting new people and loving every minute of it!<br>That's enough about me, I look forward to hearing about the rest of you! Keep me in the loop if there's any reunions that you guys are planning. Cheers!")
	
		
        L.marker([46.71109,1.7191036]).addTo(map)
                .bindPopup("<b>Becca Morack</b><br />Hey Everyone! <br>This is such a great idea! It has been really exciting to read how well everyone is doing  Thank you Kristina for putting this together!<br>I graduated in May from Parsons with a BFA in fashion design. I am moving to France next week (just for six months), to teach English in an elementary school part time, which I am really excited/nervous about, and I also have an internship lined up. <br>I will be back for the holidays and would love to hang out with everyone!")

        L.marker([33.8712698,-118.0621197]).addTo(map)
                .bindPopup("<b>Tyler Shamy</b><br />Whatsup everyone! Glad to hear everyone is doing so well. Kristina, cool idea putting this together. I'm still in LA working in the entertainment industry, but my focus has shifted to voiceover & songwriting for other artists & licensing (tv/film/commercials). I was the promo voice for a Saturday morning kids' block called Vortexx on CW for a year and a half, which was a nice, steady job. Also been doing VO gigs for various clients like Nickelodeon, MTV, McDonalds, PS3, etc. My main goal is to be a regular on an animated series though  Other than that, I've been writing songs for major artists in Asia, had a #1 with an artist in Spain, placed songs in a Lucky Charms commercial, Degrassi, etc. Ultimate goal musically is to get more 'cuts' (as the music industry calls it) with major artists in US such as the household names, so I've been working towards that. It's definitely a hustle! Anyway, I'm always back in Jersey for the holidays, so hit me up if you guys ever want to party...even if I haven't seen you since we were still going through puberty. And the peeps in LA, feel free to hit me up too! I've already been hanging with Marisa Desa out here! Much love!")
	
		
        L.marker([40.3236572,-74.141423]).addTo(map)
                .bindPopup("<b>Kristin Krukowski</b><br />Hey guys! This was an awesome idea Kristinith Eve and cool to see what everyone is up to and where they are. I am now a Mommy to 2 awesome kids and loving every single second of it! Hope all is well with everyone ")


        L.marker([26.4560078,-80.0922142]).addTo(map)
                .bindPopup("<b>Josh Barmak</b><br />I posted something quick and short but since everyone is going into details so will I. I graduated Ithaca college with a degree in film and photography concentration in cinematography I went "abroad" to LA for a semester worked at a few film companies and a netflix movie. The goal is to make to LA if not that then NYC but I got offered an apprenticeship in Miami to work with this producer from first class alliance so I am doing that for now. <br>Here's my Vimeo check some of my college work out and hopefully you will see my name up on the big screen one day as a director !<br>http://vimeo.com/m/user15912950")
	
		
        L.marker([40.42137, -74.67618]).addTo(map)
                .bindPopup("<b>Sarah Sheldon</b><br />Hi everyone!<br>I graduated last spring from Muhlenberg College and I studied Film and Neuroscience. Right after graduation I immediately drove across country to work at the IMAX corporate office in Los Angeles. I am a Digital Department Coordinator in their Post-Production department. I also do some independent screenwriting on the side.<br>It sounds like a lot of us are in LA and definitely should meet up!")


        L.marker([42.391157,-72.526712]).addTo(map)
                .bindPopup("<b>Matt Carco</b><br />Hellooooo everyone. It's been a long time since I've talked to like anyone from Monty, not sure why but hey shit happens I guess. I'm in my last year at umass amherst, and I'll have my degree in political science, and I'm trying to go to grad school after I think. This year I've been sick a lot though. Let's see, I had an ecoli infection to start off last semester and had to get surgery and a virus/lung infection to end it, and this semester I've had food poisoning three weeks ago, and I've had a 103 fever for about 8 days and I have pneumonia now. Tough goings, oh well. It'll be nice to see what everyone's been up to so I look forward to reading and also congrats to everyone starting their adult life!!")
	
	
	
        L.marker([41.0856531,-73.8097574]).addTo(map)
                .bindPopup("<b>Lisa Qian</b><br />Hey guys! Props to Kristinith for this awesome idea, it's so cool to hear about all the awesome things you guys are doing.<br>I graduated from Rutgers with a degree in Exercise Science & Sport Studies and a minor in Spanish. I got to do a lot of cool medically related things at college--volunteered as an EMT, went to Panama and Ghana for medical mission trips, worked for a plastic surgeon, did research on exercise and mental health, and did a surgical shadowing internship in CA. Got into ultimate frisbee and longboarding too haha.<br>Currently I'm a medical student at New York Medical College, about 45 min north of NYC. If any of you guys are around, hit me up! ")
	
	
        L.marker([40.404601,-74.668832]).addTo(map)
                .bindPopup("<b>Suraj Prakash Sinha</b><br />Hey yall, graduated from northeastern up in Boston this past May. While there I did econ and poli sci, and helped start a fraternity. Just started working at Bloomberg in skillman, home is indeed quite boring so if anyone's ever around and bored definitely hit me up!")
	
	
        L.marker([40.807536,-73.962573]).addTo(map)
                .bindPopup("<b>Lela Swartz</b><br />Hey everyone!!<br>It's so nice to read all of the great things that you all are doing!<br>As for me, I graduated from Lafayette College in May with a B.S. in biology. I'm now studying at Columbia University to get my masters in nutrition education. I'm not sure exactly what I'd like to do with that but I'm really interested in healthy lifestyles and disease prevention. I'm excited for what the future holds!<br>Can't wait to see everyone when we eventually have our first reunion!")
	
	
        L.marker([40.478671,-74.431789]).addTo(map)
                .bindPopup("<b>Samuel Stevens</b><br />Hey all! I was doing Air Force ROTC at Rutgers University for 2 years then I decided that wasn't for me. I took a year off and helped open a restaurant in Princeton (If you ever go to Agricola, let me know I'll try to hook you up). I'm back in college now doing Army ROTC. I'm also part of an Infantry Unit with the NJ National Guard. I graduate in a year and a semester. I'm going to the Active Army after that and I'm filling out my Warrant Officer packet now for when I graduate. I do freelance Photography here and there (models and still life, hate doing events), and I still work in restaurants. I have my own apartment in New Brunswick. It's more fun than monty. any of you stuck in Monty feel free to come up and visit!")
	
	
        L.marker([41.3264039,-87.7933079]).addTo(map)
                .bindPopup("<b>Rob Booth</b><br />Hey folks! I just finished reading through all the posts and it's awesome to see what all of you have been up to.<br>I graduated from Trinity International University in May with a BA in Christian Ministries with an emphasis on Youth Ministry. That being said I was incredibly blessed to land a Youth Pastor position right after graduating and am now the Youth Pastor of Christ Community Church in Peotone, Il, right outside of Chicago!<br>I'd love to reconnect with you so drop me a line when you can. Thanks Kristinith Eve for putting this together!<br>BTW Here's the student ministry page if you want to check it out.<br>https://m.facebook.com/MERGECCC?refsrc=https%3A%2F%2Fwww.facebook.com%2FMERGECCC&_rdr")
	
	
        L.marker([40.42137, -74.67618]).addTo(map)
                .bindPopup("<b>Pauline Bak</b><br />Hey everyone! It was really great to read about what everyone has been up to! Let's keep it going. Also, a shout out to everyone serving our country!<br>I'll try to keep this short. I graduated from Rutgers University in May with a B.A. in economics and political science. Since I've joined a program called Teach for America (some of you may have heard of it). It's a nonprofit working towards eliminating education inequity in the US. I am working as a special education math teacher in Northeast Philadelphia. Sooo as boring as Montgomery may be, this experience so far has really made me appreciate the schools that we went to and all the resources that were available to us. Oh if anyone grabbed a copy of Montgomery News in September, there's a short article there that talks about what I am doing! At nights and weekends, I am also going to graduate school at the University of Pennsylvania. My mom moved out of Montgomery while I was in college. My mom and my step dad now live in Lyndhurst, NJ (the home of Medieval Times and a five minute drive from Giants Stadium). I do get a chance to visit Montgomery once in a while though. I think that about sums it up.<br>Best of luck to everyone, especially those with brand new jobs or in their starting months of graduate school! If anyones ever in Philadelphia, feel free to let me know, I am a pretty decent tour guide. ")
	

	
        L.marker([40.382267,-74.8897285]).addTo(map)
                .bindPopup("<b>Alana Fazio</b><br />Glad to see that everyone is doing pretty damn well for themselves! I recently graduated from Cabrini College in May with a Bachelors Degree in Early Childhood Education with a minor in Special Education. I currently am working as a full time Teaching Assistant at an alternative school in West Amwell NJ. My students are 7th and 8th graders who live in Trenton and are emotionally disturbed. Its a pretty tough job but having a great learning experience! Knowing that I will try my best to make a positive impact on their lives makes me smile. However in the near future I hope to pursue my dream job as a Pre-K or Kindergartner Teacher. Fingers crossed! I am still living in Montgomery with my parents (trying to milk that as long as possible :P) and I have not a clue where life will take me but for now I am just going with the flow!<br>Best of luck to everyone!")
	
	
        L.marker([38.7125874,-78.1601284]).addTo(map)
                .bindPopup("<b>Rebecca Sasiela</b><br />Hey y'all! I graduated from Johnson and Wales, Charlotte, NC in May with a BS in baking and pastry and food service management with concentrations in sustainability, beverage, and psychology. Started working in the pastry department at The Inn at little Washington in Washington, VA. (In the middle of no where VA)")
	
	
        L.marker([39.949914,-75.2]).addTo(map)
                .bindPopup("<b>Danielle Rosenberg</b><br />Hey guys! I just graduated from Penn State in May and majored in Veterinary and Biomedical Sciences with an Equine Science minor. I am now attending University of Pennsylvania School of Veterinary Medicine. I am living in Philadelphia so if anyone is ever in the area it would be great to catch up! Glad to see everyone is doing well!")
	
	
        L.marker([40.523317,-74.440951]).addTo(map)
                .bindPopup("<b>Pooja Parkh</b><br />Hi Everyone! I read all the posts and it's really great to see everyone doing well and really happy! This was a great idea, Kristinith <br>I'll keep my story short, I am currently in my last year at Rutgers University Business School in Newark, NJ. I have interned at Enterprise Rent-A-Car as a Management Trainee and have been offered a full time position there when I graduate in May. I am keeping my options open, but I really think I will be accepting my full time offer with Enterprise and start my career there after I graduate in May. <br>If anyone comes up to Newark, Hoboken, the city, let me know and we can catch up! Enjoy the rest of your day!")
	
	
        L.marker([38.8993487,-77.0145665]).addTo(map)
                .bindPopup("<b>Christine Godinez</b><br />Hi all! I graduated from the University of Richmond down in Virginia in May with a degree in Political Science. In July, I shipped off to live in Peru for 3 months, and I just got back last Friday. Now the real job search begins - I'm looking to work for the government or an NGO in the Washington, D.C. area. The dream is to eventually become a Foreign Service Officer. Till then, I'm working at the Hallmark store in Hillsborough - come visit!")
	
	
        L.marker([40.5930775,-75.48382]).addTo(map)
                .bindPopup("<b>Tali Ramo</b><br />Well if this isn't the craziest shit I've ever seen. Kristinith, this is awesome. I love seeing where everyone's ended up! So I graduated from Muhlenberg in May (I see you, Sarah Sheldon) with a BA in Sociology, Minor in Africana Studies. I now live in Allentown, PA like 5 blocks down the road from Muhlenberg and am a Grassroots Organizer for Planned Parenthood PA Advocates. My parents moved down to Virginia a couple of years ago so going back to Montgomery is weird and rare but I try. I want to end up down by them and get a job in DC hopefully working with a progressive policy organization. Let's talk about how our 5 year reunion is in a year. Nope. Isn't it still 2007 and we're all obsessed with The Used and Death Cab?")
	
	
        L.marker([37.228384,-80.423417]).addTo(map)
                .bindPopup("<b>Patrick Hurley</b><br />Hey y'all! I am currently in my fifth year at Virginia Tech as a double major in accounting and finance. I also have a minor in international business from interning in Australia one summer. I will be graduating in May 2015 and until then will spend most of my time here in Blacksburg enjoying this victory lap. At the moment I am not sure where I will end up after I graduate but have been interviewing with CPA firms in DC, Richmond and New Orleans. Next time I'll be in monty is Thanksgiving and I look forward to catching up with y'all.")
	
	
        L.marker([40.4788424,-74.4273365]).addTo(map)
                .bindPopup("<b>Kellen Anthony Porter</b><br />Hey friends, thanks for the invite to the group! many of ya'll probably barely knew me in high school, only in the Montgomery school district for four years. Currently taking my victory lap fifth year pursuing a major in astrophysics at Rutgers University. On the side, I work with children, teaching them how to swim at a Rutgers Red Cross swimming instruction program. I plan on either graduate school to pursue a masters/doctorate in astrophysics or trying to get some work experience in a job after I graduate. There are some big things in space coming in the next century and I hope to be a leader in the charge soon.")
	
	
        L.marker([40.404601,-74.668832]).addTo(map)
                .bindPopup("<b>Courtney Elizabeth</b><br />Hi all!</br>Hope everyone is doing well! I graduated this past May from Hobart and William Smith where I was a double major in Economics and International Relations. Became really interested in finance after interning at Bank of America Merrill Lynch and Markit during college. During my junior year spring term, I went abroad to London which was an unbelievable experience. I was able to travel all over Europe and land an internship at Markit's headquarters in the center of London. I then continued my internship with them the following summer in Manhattan. Now, I am working for Bloomberg LP and I am in their Global Data Analyst Program currently rotating on their Equities' desk! I work out of the Princeton office right now but may be moving to the New York office in the next month!</br>Let's get a group together to go to the Tale or the Ivy soon!! Miss you all.")
	
	
        L.marker([40.4212899,-74.7049647]).addTo(map)
                .bindPopup("<b>Chris Nieves</b><br />Hey all,<br>Pretty cool that there is finally a place to do this. Most of you have seen me around since Kindergarden in Monty. Anyway I actually decided I liked building stuff straight out of HS so I went to Embry-Riddle Aeronautical University in Daytona Beach, FL.<br>I started interacting in a ton of clubs, but eventually decided that I liked volunteering much more. I ended up in the Greyhound Pets of America organization as well as racing in the SCCA. I found an appreciation in anything with a motor and decided to graduated with a BS in Mechanical Engineering with a specialty in High Performance Vehicles.<br>I then decided after working 1 summer job and having a son that I would rather work for myself and ended up designing my own stuff. So as soon as I graduated in May (loans right around the corner now) I setup plans for my own company. In the mean time I work for Parsons Brinckerhoff right next to Madison Square garden as an engineer so anyone in NYC that commutes via train I feel your struggle and would love to meet up with anyone in NYC.<br>I actually just launched my company check it out at Syn Innovation LLC! At the very least you get to see cool images! Currently I suck at business (maybe someone can help me out with this?) so I am just designing stuff. Currently still in Monty playing with my 3D printer everyday if anyone needs anything.<br>I really hope this page really catches on as I love to read the stories so far! Pretty awesome growing up with people and seeing where they are now!")
	
	
        L.marker([40.758895,-73.985131]).addTo(map)
                .bindPopup("<b>John Foley</b><br />Hey everyone</br>I graduated from Syracuse in May with a Dual major in Supply Chain Management and Entrepreneurship. Sophomore year I was lucky enough to intern for The Orchard, an independent music company that works with independent artists, labels, and other content providers to deliver content to iTunes, Spotify, Youtube ect. I also did work on the side (because The Orchard was unpaid) for my boss’s management company, Electric Feel Management which was the most surreal experience of my life (http://electricfeelmanagement.com/). I worked with some awesome guys like 2 Chainz, French Montana and even got in on the Carly Rae buzz working with the producers of Good Time feat Owl City. I was in charge all boring intern work like booking flights and hotels but it was amazing to be in the same room as these artists. I hope to end up working in the music industry but currently I do logistics and location planning for Ross Stores, specifically Lingerie and Hosiery... (no idea why they put me in this dept I thought it was some kind of joke).<br>I work right in Midtown by times square but still commute from Princeton Junction. If anyone needs a ride to the train or just wants to grab drinks after work hit me up. Glad to hear everyone is doing well.")
	
	
        L.marker([32.8245525,-117.0951632]).addTo(map)
                .bindPopup("<b>Brian Testa</b><br />Hi guys!</br>This group was a great idea, really cool to see what you all are up to! I graduated from Saint Joseph's University in May and studied Marketing and Economics while I was there. After visiting my older sister in LA last summer, I realized that California was the place for me. I applied to a few companies out here and was fortunate to land a job as a Buyer at UTC Aerospace Systems in San Diego, California.<br>Three weeks after I graduated, I packed my life in my car and started my trip out west with my dad. Some of the places we stopped in were St. Louis, Kansas City, Dallas, the Grand Canyon and (of course) Vegas before we ended up in SD. Hit me up anytime if you're here!<br>I'll be back over Thanksgiving and Xmas - let me know if there is something going on!<br>Best of luck to everyone!")
	
	
        L.marker([40.2885123,-74.019926]).addTo(map)
                .bindPopup("<b>Kristinith Eve</b><br />Sup playas!<br>I'm extremely exuberant that everyone is enjoying the group! Keep them posts comin' mannnn!<br>I guess its time to maybe update you on myself? haha WELL I am currently finishing up my last semester at Monmouth University and will be graduating with a major in Criminal Justice and minors in Psychology and Photography. I've been living off campus for the past two years and am literally 1.5 miles from the beach sooooo if any of ya wanna visit the jerzzzzz shore hit me up even though my schedule is pretty busy!<br>I experienced Hurricane Sandy last year first-hand, luckily no damage to my house but was powerless for 14 days [it was FREEZING], off from school for at least two weeks, and my campus was pretty destroyed. Things are essentially back to normal over here thankfully but it was extremely sad to see the destruction up close and personal.<br>ummmmmmm what else... I work at my schools center for the arts doing box office but also all the back stage work for any shows that come to the university so I've met some cool people and I just finished an internship in the investigations unit at the Office of the Public Defender in Freehold and it was awesome.... hopefully can score a job with them in the future. I'll be doing a photography senior show, which I'm pretty pumped about anddd yeah i think thats about it. still obssessed with video games and pokemon.. lets be DS friends and if any of you play destiny on the 360 lemme know!<br>Extremely excited to party with ya'll over thanksgiving break! It's great to see how much people have changed/or have not changed at all.<br>heres my flickr if you wanna check it out (needa update it)!<br>https://www.flickr.com/photos/kristinaelkington/<br>also, if you have any suggestions or ideas for the group, feel free to message me!<br>good vibes to allllllllllllll ")
	
        L.marker([40.798213,-77.859908]).addTo(map)
                .bindPopup("<b>Garrett Schwarte</b><br />Hey Everyone,<br>I'm currently attending Penn State University and in the process of getting my BS and MS in biotechnology through an integrated program (which will allow me to get both degrees in 5 years instead of 6). As part of the program I'm required to get a Co-op, which I'm 5 months into. During this time I've been living in Silver Spring, Maryland, assisting the Navy in producing a malaria vaccine. <br>After this Co-op, I plan to graduate in May of next year and to look for a job in an industrial position somewhere. Realized I'd much rather be out there talking to people about science, than just utilizing it in a lab... <br>Haven't Spoken to the vast majority of you in 4 years, if not longer, but I'm always happy to catch up. Send me a message if you're interested in meeting up and we'll see what we can do! Hope to see you all soon!")
	
	
        L.marker([37.916104,-85.956247]).addTo(map)
                .bindPopup("<b>Lara Shegoski</b><br />Kristina great idea! I've moved around a bit since 2010 I graduated from Johns Hopkins university and commissioned in the US Army . Since then lived a few random place ft. Bragg. NC and wheeler army airfield HI. Currently at ft Knox KY as a psychological operations officer . I'll be back in NJ for the holidays though! Good luck to everyone.")
	
        L.marker([37.2244654,-81.5183885]).addTo(map)
                .bindPopup("<b>Julie Smith</b><br />This is such a great idea! I graduated from Loyola University Maryland in May. Truly had the best four years of my life. I was able to walk onto the division I basketball team freshman year, played for 3 years, and decided to quit senior year, so I could really experience college. We practiced every day for 3-4 hours and traveled a lot of weekend. It just wasn't for me.<br>The morning my senior class was leaving for Dewey Beach, Delaware for our senior week (which was the week in between finals and graduation) I received an amazing job offer from Northrop Grumman. Northrop Grumman is the leading global security company. We supply a lot of defense machinery to the military. My office is in Washington, D.C., so I'm currently living in northern VA. All of my friends from school got jobs in NYC, so it kind of sucked moving to a city I wasn't familiar with and having no friends in the area. I'm running in the Princeton half marathon on Nov 2nd, and spend a lot of my free time running, so I probably wouldn't have that big of a social life anyway.<br>I also plan on going back to school part-time in the spring to get my MBA.<br>Alright, by now a lot of you probably stopped reading and don't care to hear more about my life... I'll be home for Thanksgiving and Christmas, so if anyone wants to catch up, let me know!")
	
	
        L.marker([39.9543596,-75.1896221]).addTo(map)
                .bindPopup("<b>Brian Dougherty</b><br />Hey Guys!<br>I graduated from Drexel in Philly in the winter of 2012 with a BS in health sciences. I worked for 6 months at a Physical Therapy place in philly and then started Physical Therapy school that fall at Drexel. So I am really only a short car ride away. I am in the first term of my second year here. I want to work with injured military and athletes. I have one year left before I graduate in march of 2016 with my Doctorate in PT. I head out for clinicals in the spring and next fall. I will be in Albuquerque, NM (so if anyone has been out there and has any suggestions for anything let me know!) and then I will be at Fort Bragg, NC next fall. I look forward to catching up with you guys on break if you are in the area and if you are ever in Philly send me a message and maybe we can grab a beer!<br>Best of luck to everyone!")
	
        L.marker([47.6062095,-122.3320708]).addTo(map)
		.bindPopup("<b>Kevin Li</b><br />What's up ya'll! It's been too long. Really great to see everyone doing so well and doing some really really cool things (we're super diverse!) I graduated from the University of Texas this past may with a degree in econ and math. From there I moved to the pacific northwest to work for this small company called Amazon? I work as an program manager in Fulfillment by Amazon so if any of you guys sell through that, that's my part of Amazon! Living in Seattle has been pretty dope and if you guys ever make it out here hit me up for sure! I'll be back during the christmas time and hope to see some people! looking forward to the reunion ya'll!")


L.marker([41.886628,-87.635017]).addTo(map)
                .bindPopup("<b>Merry Xiao</b><br />hi guys! this is really cute and giving me all the feels.<br>i graduated from northwestern this past june with a ba in economics and mathematical methods in the social sciences and a kellogg certificate in financial economics (basically i did a lot of math and econ). i spent the summer traveling (alaska, vancouver, dublin, london, paris), bumming at home, and studying for the gmat.<br>i just started as a consultant in the health practice at Strategy& (formerly known as Booz&co) a couple of weeks ago in chicago, so if anyone's coming out soon lmk! Carolyn and i will hang out with you. i'll also be back for thanksgiving and christmas as well. nice hearing from all of you!<br>also: anyone ever in bulusu's class, i now work with someone who looks identical to him and i'm tempted to ask him to say the word 'yellow'")
	
        L.marker([41.2984165,-72.9290959]).addTo(map)
                .bindPopup("<b>Michael Thomas</b><br />Hey Guys!<br>It is great to hear everyone has had a blast these last few years! I am a recent grad of Johns Hopkins University where I majored in Mechanical Engineering and minored in Entreprenuership and Management (fancy unnecessary name for what is a business minor). I swam a few years in college but unfortunately had to stop after I tore my labrum (somehow I found a way to get injured in swimming). My curiosity of how sports injuries occur made me shift towards a more biology inspired approach of my major and led to what I do now. Last summer I worked in the Orthopaedics division of Stryker up in Mahwah, NJ and more recently am staff at Yale doing research in pursuit of a PhD. My research is Dept. of Defense sponsored and is focused on making affordable prosthesis and medical bio-robotic systems for wounded veterans. Thus, I have an overwhelming appreciation for everyone of the class of 2010 that joined the military. Besides that I currently live in Connecticut but frequent Monty because my family still lives in the area (and New Haven is boring as shit). My family seems to decide to go on vacations without me so I haven't been around much since High School but its great to see the cool places everyone has traveled. If you all want to meet up Thanksgiving weekend maybe we can assemble something at Tigers Tale or something?<br>This thread was a great idea and I hope that everyone is doing well!")
	
	
        L.marker([38.9071923,-77.0368707]).addTo(map)
                .bindPopup("<b>Christian Benz</b><br />Hey everybody!<br>I'm glad to hear people are doing well. I graduated in May from The George Washington University with a BS in Civil Engineering and a concentration in Sustainability. I was lucky to get a job offer in the fall of senior year so I had an awesomely fun and relaxing spring semester. I was home in Montgomery for the summer and started working full time in DC in August. I am a Field Engineer for Turner Construction (out of the DC office) and I am currently building a health clinic for the Navy in Annapolis. Luckily I have a car so I get to make the trip home whenever I want. I'd love to hang out during the holidays when I get some decent time off work. I look forward to hearing from the rest of you!")
	
        L.marker([40.470421,-74.4100751]).addTo(map)
                .bindPopup("<b>Kelly Lynne</b><br />Hey hey,<br>it's great to hear what people are up to, a lot of it is unexpected and awesome!<br>I graduated from University of Vermont in May with a BA in Psychology and a minor in Chinese. I spent a semester studying Mandarin Chinese in Kunming, China and really enjoyed it, I would love to live there someday. If anyone speaks Mandarin hit me up! I could definitely use some practice lol.<br>My family moved to Lambertville so that's where I'm currently living. I work for Easter Seals New Jersey, which is a nonprofit organization that provides support/guidance to people with mental illnesses and disabilities. I work at residential group homes for adults and help them work towards gaining greater independence and stability. <br>Not sure what the future's looking like for me... I may go for my Master's in Counseling or Art Therapy but I'm still trying to figure things out. I'm in the dirty jerz for the time being though, so it'd be nice to catch up with some of you!")
	
	
        L.marker([40.4965332,-74.4983848]).addTo(map)
                .bindPopup("<b>Josh Prevost</b><br />Hello fellow Montgomerians,<br>Congrats to all of you who have posted so far! Seems like everyone is doing well for themselves in the post-college world. <br>I graduated from Seton Hall University this past May like most of you. I played baseball there for all four years and this past year was named Big East pitcher of the year and an All-American which was pretty cool. I was drafted in the 5th round by the New York Mets in June and currently in their minor league system doing my best to make it to the big leagues.<br>It's the 'off season' right now so I'm home in Montgomery most nights so if any of you want to catch up and share a beer just let me know!")
	
        L.marker([24.0892689,-75.2443269]).addTo(map)
                .bindPopup("<b>Michael Goldman</b><br />Glad to hear of everyone's success. Graduated in May from Miami (OH) with a BA in organizational communication and minor in management. Accepted my job offer in february of senior year and my contract started mid september. Currently working onboard Royal Caribbeans Allure of the Seas as event management staff. I plan, organize, and host shows, activities, and meetings in front if a microphone 10 hours a day. Currently we're sailing eastern and western caribbean cruises but switching itineraries to Europe in the spring, specifically meditteranean area. I'll be onboard for 2 contracts of 5 months each with a 2 month vacation in between. After the rotational period I'm moving back to Miami, Fl to continue working with the company at the headquarters where I interned the summer after junior year. The plan is to work at the corporate office for 2 years and return to grad school for a masters in hospitality. If you're planning a cruise in the future and want some help, don't hesitate to contact me.")
	
	
        L.marker([41.311874,-72.927882]).addTo(map)
                .bindPopup("<b>Greg Cui</b><br />hey everybody, really glad we're doing this. I miss you all and have been terrible about keeping in touch, so having this space is terrific. I just graduated from Rutgers with a B.A. in econ. At Rutgers, I spent most of my time competing with the mock trial team and researching legal policy affecting ex-offenders (record expungement, in particular). I then sneaked past a few admissions committees and am halfway through my first semester of law school. I spent the summer wandering around Italy and camping in the National Parks - unforgettable experiences. A perk of staying on a school schedule is that I return to Montgomery regularly for your typical breaks - Thanksgiving, winter, spring, etc. - and would love to see you if you are around and have time. Looking forward to talking soon.")
	
        L.marker([42.339807,-71.089172]).addTo(map)
                .bindPopup("<b>Chris Fisher</b><br />What's up! I'm currently a senior at Northeastern University in Boston. I am on my 3rd co-op at Instron working that 9-5. I'll be graduating in May with a BS in Mechanical Engineering and a minor in Business. My parents moved to Virginia, then to New Hampshire, so I don't think I'll be back to Monty anytime soon. But who knows, maybe I'll get a job in the area after I graduate. My other co-op's were at MIT Lincoln Laboratory and GE Aviation if you all need some contacts for job applications...")
	
	
        L.marker([40.4980709,-74.6849885]).addTo(map)
                .bindPopup("<b>Anna McCall</b><br />I graduated in December 2013 with a BA in Psychology out on Long Island. I lived there for 2 years after I transferred from Rochester. Summer before my last semester I decided that psych wasn't what I wanted to do so I am now doing my prerequisites for nursing school. I am hoping to get into an accelerated BSN program next year. I currently live in a wonderful little apartment on a farm in Hillsborough with my boyfriend and work as a nursing assistant at Princeton Medical Center on the Telemetry unit. I like it there and plan to stay with UMCPP after getting my RN until my boyfriend is done with his PhD . I never thought I'd be back to Jersey, not to mention passing MHS every day.")
	
        L.marker([35.920959,-79.0392909]).addTo(map)
                .bindPopup("<b>Jordan Sasiela</b><br />Howdy everybody! Sooo I went UNC Chapel Hill, and graduated with a BS in Psychology and a BA in Math, so you know, super fun. I also studied abroad in Italy, and am currently working on becoming fluent because I would like to live there next year and possibly later in life. Right now I’m still in Chapel Hill working as a Psych Research Assistant and Recruitment Coordinator for a company called TeleSage, but after next year I will be returning to Grad School to get my PhD in Clinical Psychology. My family still lives in NJ, but they moved up north which is why I’m never in Monty any more… sorries.. Oh, and I have a puppy!! His name is Ash ")
	
	
        L.marker([40.488377,-74.4409678]).addTo(map)
                .bindPopup("<b>Eric Whyluda</b><br />I graduated university of vermont as a mechanical engineer and now working for an engineering consulting company and currently contracted out to another company as the staff engineer there... living in Monty now l but moving to New Brunswick soon- hmu if anyone else is trying to move there im looking for a room mate for plaza square")
	
        L.marker([40.3998568,-74.6965795]).addTo(map)
                .bindPopup("<b>Hillary Spohn</b><br />Hi everyone! This is really great, I'm enjoying reading everyone's stories. I graduated in May from the George Washington Univeristy and studied International Affairs concentrating in International Development with minors in Socio-Cultural Anthropology and Spanish. This led me to study abroad in Seville, Spain- honestly the most beautiful place I've ever been. I haven't been around much because every summer since I started at GW I stayed down in DC interning (so if any of you end up there and need living or restaurant advice I'm your girl, ask Julie Smith). But for the past 5 months I've been living at home... it's been very very strange. I am commuting into the city and work at Marsh Brokerage as a non-profit client representative. In the long-run I want to start my own non-profit that promotes education to women in Latin America sooo I probably will be reaching out to all you successful tycoons to be investors (haha). I move into FiDi of Manhattan next week!!! So if you are in the city and want to meet up for happy hour let me know! And best of luck to everyone!")
	
	
        L.marker([32.391267,-84.822907]).addTo(map)
                .bindPopup("<b>Ian MacPherson</b><br />Hey all,<br>I graduated from West Point in May and branched infantry. I moved down to fort benning, Georgia to do some training and just graduated from ranger school on Friday. Needless to say it's nice to be back in the real world. I'll be here for another six months or so until I move to Vicenza, Italy for my first assignment with the 173rd airborne. Yeah, thanks for paying your taxes...<br>Anyone's welcome to crash at my house if you're passing through, same goes for when I'm in Italy. I'm sure I'll see most of you at the ivy or triumph over thanksgiving. Looking forward to it.")
	
        L.marker([42.346595,-71.089529]).addTo(map)
                .bindPopup("<b>Chris Restanio</b><br />Hey guys, I'm happy to hear you're all doing well and surviving life after college, it makes me a little less nervous for when I'm finally done in December. I'm finishing up my last semester at Berklee College of Music in Boston, which means I can do pretty much whatever I want right out of school, like be a barista or a gas station attendant or a homeless guy with clever signs like 'if you read this you owe me 5 dollars'. Assuming things go well, I'm gonna try for a job at The Echo Nest which is a music technology company located in Somerville, Massachusetts, where I interned last summer. I've been releasing my own music (www.chrisrestaino.bandcamp.com) for free, and I'm in a band called Vitamin Sun. We're gonna be in the studio recording our first full length in the beginning of December, and we'll have it out in early 2015. If you like what you hear you can like our page for updates and videos and info on shows we're playing and all that kinda stuff. I'm in Boston most of the year so if anyone's up here I'm down to clown, or have a serious conversation, either way. Otherwise I'll be home for the holidays so we can grab that obligatory beer everyone is posting about.<br>More shameless self promotion in the form of a video we recorded last weekend: https://www.youtube.com/watch?v=yeGWvN1MFzE")
	
	
        L.marker([40.9123761,-73.1233889]).addTo(map)
                .bindPopup("<b>Dhaiyasheel Ghosalkar</b><br />Sandy over here. Glad to see everyone is doing well. I graduated in May with a bio degree. Since August I've been working as an ER scribe at a hospital in PA while living in Monty. I just got into SUNY Stony Brook medical school today. Not 100% sure if that's where I'll end up but glad to have something in hand. If you're in the Princeton area hit me up.")
	
	
        L.marker([47.6345618,-122.3569974]).addTo(map)
                .bindPopup("<b>Dylan Ayrey</b><br />I'm pretty sure I was a creep and/or an asshole to any and everyone in high school and I'm sorry to the people who remember me. I'm living in Seattle. I was living in Boston and before that I was living in Rochester. I'm working full time for a company, doing a job I can only describe as 'Ethical Computer Hacker'. Before that I was a full time software developer. I'm going back to school in Rochester this February and will be done with my undergrad in 2015. I've been into American Sign Language and Deaf Culture lately.")
	
	
        L.marker([40.7483002,-73.751668]).addTo(map)
                .bindPopup("<b>Lauren Geary</b><br />Thanks Kristinith Eve for putting this together! So nice to read what everyone's been up to. Like most of you I graduated in May. I graduated from Quinnipiac with a Bachelor of Arts in public relations and a minor in international business. I currently work as a marketing executive for an international events and conference company that's located in New York City. I work on all the financial events, so it's been fun and a learning experience. Still living in Montgomery for the time being but will probably move some where in the city in the next few months. Hope to see some of you around either in Montgomery or the city!")
	
	
        L.marker([40.287039,-74.666783]).addTo(map)
                .bindPopup("<b>Annie Herman</b><br />Can’t say I don’t miss singing the national anthem at football games, hosting the sports announcements, and powderpuff football… those were the days. I graduated from Rhodes College in Memphis, TN and I also spent a semester studying at NYU in Madrid. In college, I became a certified group fitness instructor and taught a variety of classes in the athletics dept. I spent a summer serving as a corporate wellness coach at Verizon Wireless’ National Corporate HQ. I realized that corporate wellness was just a small part of HR, a field I was interested in, so I decided to explore various facets of the field the following summers at Country Music Television (CMT) in Nashville, TN and at Baker Donelson, a leading southern law-firm.<br>I am now back in Princeton working as a Human Resources Associate at Dow Jones & Company / The Wall Street Journal. I am in an HR Rotational Program and I am diving into four areas of HR over the course of a year before specializing in one set area. Outside of work, I am a member of the Princeton Junior League, and I am also studying for my CPT exam through the National Academy of Sports Medicine. I work both in Princeton and in NYC, so I am around most days and would love to catch up and reminisce!")
	
	
        L.marker([35.129186,-89.9696395]).addTo(map)
                .bindPopup("<b>Kendra Lyons</b><br />Hey everyone! Congrats on all of your successes. I can't say I'm surprised at all to hear that everyone is doing such great things. I graduated from Rhodes College with a degree in Political Science and now am a 1L at University of Memphis Law. I hope to be an Entertainment lawyer someday, but I will probably change my mind several times about that before graduation. I live in downtown Memphis with the cutest roommate ever. She's a black lab/pitbull mix named Bella. I founded theGRIND, LLC (www.thegrindmemphis.com) my senior year at Rhodes. It's an online magazine about all things Memphis from the young adult perspective. We also put on events and are working on publishing a book and getting the magazine in print. My dad moved to Oklahoma City about a year ago and my mom is still in Princeton, so I don't get to go home nearly as often as I'd like, but I will be in Princeton for Thanksgiving, so I'm looking forward to seeing everyone then! If you love music, history, and fried chicken/BBQ I HIGHLY recommend Memphis to you. Please let me know if you're ever in the area!")

        L.marker([42.422146,-76.49508]).addTo(map)
                .bindPopup("<b>Nick Warner</b><br />Hey people! I graduated Ithaca College this past spring with a degree in Business Administration and a Management Concentration. I also got an Audio Production minor. I swam competitively all 4 years despite destroying my knee sophomore year. I tore nearly everything in my knee and now have metal holding it together but somehow managed to make varsity all 4 years. I am currently continuing to study. I am getting my Masters in Business Administration at Ithaca and I am expected to complete it by August 2015.<br>I work at Jungle City Studios and Oven Studios in NYC when I am not at school. Jungle City and Oven Studios are Alicia Key's studio and I got to work with a few no names like Justin Timberlake, Jay Z, Beyoncé, Nick Jonas, Pharrell Williams, Nicki Minaj, Drake and many more! It has been absolutely an opportunity and experience of a life time. When someone like that asks you to make them coffee you really can’t complain… not only because then you will get fired but hey, you’re making Beyonce’s coffee and tea. Someones gotta give Nicki and B that caffeine so they can shake it like they do... I plan to work in the music industry with the ultimate goal of being a producer and recording engineer.<br>You can listen to some of my work on my YouTube… Some more shameless self promotion https://www.youtube.com/NickWarnerMusic<br>Keep the updates coming! I should be home for Thanksgiving and Christmas as well.")

        L.marker([38.435092,-78.869755]).addTo(map)
                .bindPopup("<b>Sarah Van Peenen</b><br />Hey friends! props to Kristinith Eve for this! It's wonderful to hear about everyone's successes.<br>I graduated from JMU in May with my Bachelors in Interdisciplinary Studies and am still at JMU in the process of completing my Masters degree in Elementary Education. It's been quite the experience down here in the sticks and I've learned so much from the community. I've had some pretty great opportunities that have reaffirmed my goal of becoming a teacher, such as interning with Teach For America in Philly, a field placement in Florence, Italy in an Elementary school for a semester, and my practicum placements here in Harrisonburg, of course! Definitely starting to get sad that I will be leaving in just a few weeks to student teach in Northern Virginia but so excited for what's to come. If anyone's in the D.C. or Northern Virginia area and wants to catch up, let me know!<br>Both my parents booked it out of Montgomery when Mia graduated, but i still crash at Hillary Spohn and Annie Herman's so maybe i'll see some of y'all over Thanksgiving/Xmas time.")

        L.marker([40.5566585,-105.067652]).addTo(map)
                .bindPopup("<b>Lauren Mehl</b><br />Hey all!<br>So I'm not sure how many of you remember me (I moved from Monty to Colorado right before our senior year) but I definitely lost touch with most MHS people and it's really great to hear about all of your amazing endeavors/successes!! Since moving I've been kind of all over the place. I'm currently finishing up school at Colorado State University with a degree in Studio Art and Education. I recently moved back to Colorado from San Diego where I was working as an executive assistant at a real estate & interior design firm. Since returning, I started up a small event photography and photo booth rental business with my boyfriend to pay the bills while in school. That has been going pretty well and we are actually expanding our brand out to Arizona this coming month. Outside of all that, I've just been enjoying CA & CO and all that they have to offer. I haven't been back to NJ since moving but will hopefully be making my way out there this summer on a road trip and would love to see some familiar faces. Also, if anyone ever happens to pass through Fort Collins, CO (long shot?) I'd love to catch up.")

        L.marker([39.9587983,-75.1966472]).addTo(map)
                .bindPopup("<b>Ana Peterhans</b><br />Hey everyone! Congrats to all of you on all the great things you've accomplished! So I graduated from Tulane University in May with a BS in Public Health and a minor in Molecular Biology. Sadly, I decided to leave New Orleans (everyone should go visit at least once - its so much fun), but I moved to Philly in August and now I'm at University of Pennsylvania getting my Masters degree in Public Health with a concentration in Epidemiology. So basically I go to class every day and talk about ebola... fun stuff!<br>But anyway, my parents still live in Montgomery so I'm there visiting from time to time and I'm always down to catch up with whoever's around. Also if anyone in Philly area wants to catch up, just let me know!")

    L.marker([43.74729, -73.75122]).addTo(map)
            .bindPopup("<b>TJ VanLiew</b><br />Hey guys. I live in the middle of Vermont where I am a proud lumberjack and father of 8. I am teaching my kids to be decent viking raiders. We live in the woods and hunt for food. I use the internet by strapping an SD card to a falcon's tallon, which is why it took my so long to post this.")

    L.marker([40.523447,-74.470906]).addTo(map)
    	    .bindPopup("<b>Lindsey Milch</b><br />Hey everyone! It's good to see how far we've all come. <br>I just graduated from Quinnipiac where I majored in Biomedical Science. There I was heavily involved with Relay for Life as the Ceremonies Coordinator and also tutored in mathematics. I'm currently back at home going to Rutgers School of Public Health to get my MPH in epidemiology and would like to double major in biostatistics. Soon I'll be starting fieldwork where I would like to work in the reproductive or maternal/child health area. Hopefully one day I'll find myself at a major health organization like the CDC or WHO, but I'm loving the public health area and look forward to seeing where it takes me.<br>Best of luck to everyone with their future endeavors!")

    L.marker([39.953984,-75.173467]).addTo(map)
    	    .bindPopup("<b>Connor Andres</b><br />Hey guys I am glad to see everyone is doing so well! I graduated from Ursinus college with a major in Business and Economics. I played soccer and track throughout all four years at school. I am currently living in center city Philadelphia working for PWC in the Risk Assurance practice. If you guys are ever in the city let me know and we can catch up and grab a drink!")

    L.marker([40.7127837,-74.0059413]).addTo(map)
    	    .bindPopup("<b>Robi Cai</b><br />Well it's 6:30 AM and I just got back from the office, and since I'll be back there in a couple of hours anyway figured I check this out before taking a quick nap.<br>Only glanced through a few of these, but already love what I see - it's great seeing all of the awesome paths people have chosen. Back in May, I obtained a piece of paper with some words (among which were 'Economics' and 'Psychology') and some weird Latin phrases. At school, I got a few brain cells knocked out of my head as a member of the boxing team (thereby negating my education), helped run an organization (China Care) dedicated to improving the lives of orphans in China and helping adopted orphans in the US adjust to their new country, and worked as a research assistant to a business school professor on the nature of CEOs.<br>I've since moved to NYC where I spend most of my days sitting in a cubicle breaking my keyboard and crashing my computer with Excel. Somehow, my actions contribute to large companies merging together.<br>If you're ever in the city, definitely reach out! Would love to hear about everything that's been going on since our younger days en la escuela secundaria (my Spanish is already going down the drain..). My parents still live in Monty too, so I'll be back for the occasional holidays. Best wishes to all of you and hope to see you soon!")

    L.marker([40.505249,-74.45322]).addTo(map)
    	    .bindPopup("<b>Katie Best</b><br />Hi everyone! Congratulations on all of your accomplishments, it's so great reading all of your stories. I graduated from Rutgers in May with a degree in Communications and minor in Digital Communication, Information, and Media Studies (or DCIM, for short). I interned for a couple of advertising agencies in their media planning departments, for one I was on the Walmart account and the other on the Nestle waters account including Nestle Pure Life, Poland Spring, Deer Park, Nestea, etc. I also did a marketing internship for This Old House magazine, a good read for those moving into new places and need some ideas for DIY home projects or home improvements. During the summer of 2013 I studied abroad in Rome taking courses in art history which was one of the most rewarding experiences of my life and I cannot wait to go back. Currently I am pursuing a Masters in Communication with a focus on digital communication at Rutgers, therefore I am living in Montgomery. It would be great to catch up with those still in or around the area so hit me up whenever! It'd be awesome if we could create some event for Thanksgiving Eve since it seems a lot of people will be around for the holidays!"[]

    L.marker([40.7479061,-73.9662875]).addTo(map)
    	    .bindPopup("<b>Jillian Mary</b><br />Hi everyone! So nice to hear what you all are up to! I'm currently doing a victory lap at University of Richmond for indoor and outdoor track. My goal is to make it to NCAA finals in the 5k/10k this year. But other than that, I'm majoring in accounting and management and recently accepted a full time offer with PricewaterhouseCoopers in NYC with their core assurance department. So basically, like Ryan, I'll be one of those auditors people seem to hate, but I promise we're actually doing some really interesting stuff! I don't get to come home a lot anymore, but I'll be back in Monty for thanksgiving so I'm sure I'll see a lot of you then!")
    L.marker([40.0141905,-83.0309143]).addTo(map)
    	    .bindPopup("<b>Sowmya Takkellapati</b><br />Hi everyone! This was a great idea and it's cool to see all the amazing things you all are doing! I graduated with a degree in biology from the University of Massachusetts and was pretty involved on campus. I did mostly community service based and leadership activities. I spent much of my time working with mental health services, schools/boys and girls clubs, and the Red Cross. Most of my activities there along with my degree solidified my decision to pursue pharmacy and I am now at The Ohio State University for the Doctor of Pharmacy Program. Hope all of you are doing well! ")
    L.marker([40.503744,-74.831961]).addTo(map)
    	    .bindPopup("<b>Car Ly</b><br />Hello everyone! So crazy hearing what everyone's been doing! So I graduated in May from Penn State with a major in Secondary Mathematics Education. During my 4 years at school I had a lot of great experiences. 2 summers ago I went to Beijing, China where I ran my own summer camp for 3 weeks. I taught English to a group of 10 chinese kindergarteners and taught them about English (American) sports. Last fall I had my student teaching experience in a high school in Pittsburgh so I lived by myself there for 4 months, but kinda loved Pittsburgh. My parents moved out of Montgomery last fall to Branchburg (Somerville) so I am currently living here. And yes, it's just as boring as Montgomery. After a very very short job search in June I was fortunate enough to get a full time job offer at J.P. Case Middle School in Flemington. So currently I am a 7th grade Math Teacher (with a 10 minute commute). And I am quickly realizing how annoying I was as a middle schooler (and high schooler too). I love teaching even though it's so exhausting and there definitely is never a dull moment with a day full of 7th graders. <br>I hope to see some of you around during the holidays if you're back home!! Good luck to everyone in their endeavors!")
    L.marker({}).addTo(map)
    	    .bindPopup("<b></b><br />")
    L.marker({}).addTo(map)
    	    .bindPopup("<b></b><br />")
    L.marker({}).addTo(map)
    	    .bindPopup("<b></b><br />")
    L.marker({}).addTo(map)
    	    .bindPopup("<b></b><br />")

    L.marker({}).addTo(map)
    	    .bindPopup("<b></b><br />")

    L.marker({}).addTo(map)
    	    .bindPopup("<b></b><br />")

    L.marker({}).addTo(map)
    	    .bindPopup("<b></b><br />")
}

